name: compound

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  compound:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm start
        env:
          FTX_API_KEY: ${{ secrets.FTX_API_KEY }}
          FTX_SECRET: ${{ secrets.FTX_SECRET }}
          FTX_LENDABLE_COINS: ${{ secrets.FTX_LENDABLE_COINS }}
          FTX_STAKABLE_TOKENS: ${{ secrets.FTX_STAKABLE_TOKENS }}
          PROXY: ${{ secrets.PROXY }}
