name: compound

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  compound:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-${{ hashFiles('**/package-lock.json') }}
      - run: set -e
      - run: npm ci
      - run: npm start
        env:
          FTX_API_KEY: ${{ secrets.FTX_API_KEY }}
          FTX_SECRET: ${{ secrets.FTX_SECRET }}
          FTX_LENDABLE_COINS: ${{ secrets.FTX_LENDABLE_COINS }}
